apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-gui
  name: inventory-gui
spec:
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: inventory-gui
  type: LoadBalancer
