apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-api
  name: inventory-api
spec:
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: inventory-api
  type: NodePort
